'use strict';
const {products,bundles}=window.SHOP_DATA;
const M=window.SHOP_MATH;
const byId=id=>products.find(p=>p.id===id);
const el=id=>document.getElementById(id);
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=cents=>(cents/100).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2});
const icon=name=>`<svg aria-hidden="true"><use href="assets/original-icons.svg#${name}"/></svg>`;
const stateKey='north-resident-shop-v2';
let state={cart:[],favorites:[],compare:[]};
try{const saved=JSON.parse(localStorage.getItem(stateKey)||'null');if(saved){state.cart=(Array.isArray(saved.cart)?saved.cart:[]).filter(x=>typeof x.key==='string'&&/^[pb]:[a-z]+$/.test(x.key)&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=99&&((x.key.startsWith('p:')&&byId(x.key.slice(2)))||(x.key.startsWith('b:')&&bundles.some(b=>b.id===x.key.slice(2)))));for(const key of ['favorites','compare'])state[key]=[...new Set((Array.isArray(saved[key])?saved[key]:[]).filter(id=>byId(id)))].slice(0,key==='compare'?4:21);}}catch{}
let filter='all';let sort='recommended';let query='';let activeRoom='kitchen';let currentPanel='';let toastTimer;
function save(){try{localStorage.setItem(stateKey,JSON.stringify(state));}catch{}}
function toast(text){clearTimeout(toastTimer);el('toast').textContent=text;el('toast').hidden=false;toastTimer=setTimeout(()=>{el('toast').hidden=true;},2600);}
function priceMarkup(p){return `<div class="price-label">Цена для жителя</div><div class="price">${fmt(M.cents(p.price))} <span class="currency">р.</span></div><div class="old-price"><del>${fmt(M.cents(p.regular))} р.</del><span class="discount-tag">−${M.discount(p)}%</span></div><div class="saving-line">Экономия <strong>${fmt(M.cents(p.regular-p.price))} р.</strong></div>`;}
function bonusMarkup(cents){return `<div class="bonus-line"><span>${icon('bonus')}10% бонусами</span><strong>+${fmt(Math.round(cents*.1))}</strong></div>`;}
function productCard(p){const inCart=state.cart.some(x=>x.key==='p:'+p.id);return `<article class="product-card" data-card="${p.id}"><div class="product-topline"><span class="product-badge">Цена Северного Берега</span><button class="favorite-button" data-favorite="${p.id}" aria-label="${state.favorites.includes(p.id)?'Удалить из':'Добавить в'} избранное: ${esc(p.model)}" aria-pressed="${state.favorites.includes(p.id)}">${icon('favorites')}</button></div><button class="product-image" data-detail="${p.id}" aria-label="Подробнее: ${esc(p.model)}"><img src="${p.image}" width="250" height="160" loading="lazy" alt="${esc(p.type+' '+p.model)}"></button><button class="product-title" data-detail="${p.id}">${esc(p.type)}<span>${esc(p.model)}</span></button><p class="product-specs">${p.specs.slice(0,2).map(esc).join(' · ')}</p><div class="card-offer"><div class="card-price-row"><div class="price">${fmt(M.cents(p.price))} <span class="currency">р.</span></div><span class="discount-tag">−${M.discount(p)}%</span></div><div class="card-price-context"><del>${fmt(M.cents(p.regular))} р.</del><span>Выгода ${fmt(M.cents(p.regular-p.price))} р.</span></div>${bonusMarkup(M.cents(p.price))}<div class="card-actions"><button class="button ${inCart?'in-cart':''}" data-add="p:${p.id}">${inCart?'В корзине':'В корзину'}</button><label class="product-comparison"><input type="checkbox" data-compare="${p.id}" ${state.compare.includes(p.id)?'checked':''}>Сравнить</label></div></div></article>`;}
function bundleCard(b){const t=M.bundleTotals(b,products);return `<article class="bundle-card"><div class="bundle-gallery"><span class="bundle-count">${b.tag}</span><div class="bundle-main-image"><img src="${byId(b.items[0]).image}" width="150" height="160" loading="lazy" alt="${esc(byId(b.items[0]).model)}"></div><div class="bundle-support-images">${b.items.slice(1).map(id=>`<button data-detail="${id}" aria-label="${esc(byId(id).model)}"><img src="${byId(id).image}" width="85" height="85" loading="lazy" alt="${esc(byId(id).model)}"></button>`).join('')}</div></div><div class="bundle-card-body"><h3>${esc(b.title)}</h3><p class="bundle-caption">${esc(b.caption)}</p><ul class="bundle-item-list">${b.items.map((id,i)=>`<li><span>${i+1}</span><button data-detail="${id}">${esc(byId(id).type)} <b>${esc(byId(id).model)}</b></button></li>`).join('')}</ul></div><div class="bundle-purchase"><div class="bundle-price-heading"><span>Цена за комплект</span><span class="bundle-discount">Ещё −5%</span></div><div class="price">${fmt(t.price)} <span class="currency">р.</span></div><del class="bundle-original">${fmt(t.regular)} р.</del><div class="bundle-saving">Экономия ${fmt(t.saving)} р.</div><div class="bundle-extra">Из них ${fmt(t.extra)} р. — скидка за комплект</div>${bonusMarkup(t.price)}<button class="button" data-add="b:${b.id}">Купить комплект <span>→</span></button></div></article>`;}
function renderCatalog(){let list=products.filter(p=>(filter==='all'||p.category===filter)&&(!query||(p.type+' '+p.model+' '+p.brand).toLowerCase().includes(query.toLowerCase())));if(sort==='price-up')list.sort((a,b)=>a.price-b.price);if(sort==='price-down')list.sort((a,b)=>b.price-a.price);if(sort==='saving')list.sort((a,b)=>(1-b.price/b.regular)-(1-a.price/a.regular));el('catalog-grid').innerHTML=list.map(productCard).join('');el('results-count').textContent=`Показано ${list.length} из 21`;el('catalog-heading-count').textContent=list.length;el('empty-state').hidden=list.length>0;document.querySelectorAll('[data-filter]').forEach(b=>{const on=b.dataset.filter===filter;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});}
function setFilter(value){filter=value;query='';el('search').value='';renderCatalog();el('catalog-menu').hidden=true;el('catalog-button').setAttribute('aria-expanded','false');}
function updateStateUI(){const total=M.cartTotals(state.cart,products,bundles);for(const [id,count]of[['cart-count',total.count],['mobile-cart-count',total.count],['favorites-count',state.favorites.length],['compare-count',state.compare.length]]){el(id).textContent=count;el(id).hidden=!count;}document.querySelectorAll('[data-favorite]').forEach(b=>{const on=state.favorites.includes(b.dataset.favorite);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',`${on?'Удалить из':'Добавить в'} избранное: ${byId(b.dataset.favorite).model}`);});document.querySelectorAll('[data-compare]').forEach(b=>b.checked=state.compare.includes(b.dataset.compare));document.querySelectorAll('.product-card [data-add]').forEach(b=>{const on=state.cart.some(x=>x.key===b.dataset.add);b.classList.toggle('in-cart',on);b.textContent=on?'В корзине':'В корзину';});save();}
function addToCart(key){const line=state.cart.find(x=>x.key===key);if(line){if(key.startsWith('p:')){openPanel('cart');return;}line.qty=Math.min(99,line.qty+1);}else state.cart.push({key,qty:1});updateStateUI();toast(key.startsWith('b:')?'Комплект добавлен. Дополнительная скидка применена.':'Товар добавлен в корзину');if(el('panel-dialog').open&&currentPanel==='cart')renderPanel();}
function openDialog(dialog){document.querySelectorAll('dialog[open]').forEach(d=>{if(d!==dialog)d.close();});dialog.showModal();document.body.classList.add('modal-open');}
function productDetail(id){const p=byId(id);if(!p)return;el('product-dialog-content').innerHTML=`<div class="product-detail"><img class="detail-image" src="${p.image}" width="400" height="400" alt="${esc(p.model)}"><div class="detail-copy"><span class="product-badge">Предложение для Северного Берега</span><h2 id="product-dialog-title">${esc(p.type)} ${esc(p.model)}</h2><ul>${p.specs.map(s=>`<li>${esc(s)}</li>`).join('')}</ul>${priceMarkup(p)}${bonusMarkup(M.cents(p.price))}<button class="button" data-add="p:${p.id}">В корзину</button>${p.sourceUrl?`<a class="source-link" href="${esc(p.sourceUrl)}" target="_blank" rel="noopener">${p.sourceType==='manufacturer'?'Характеристики у производителя':'Оригинальная карточка на 5element.by'} ↗</a>`:''}<p class="detail-note">Цены и бонусы в макете ориентировочные.</p></div></div>`;openDialog(el('product-dialog'));}
function cartItem(line){const bundle=line.key.startsWith('b:');const p=bundle?bundles.find(b=>b.id===line.key.slice(2)):byId(line.key.slice(2));const total=bundle?M.bundleTotals(p,products):{price:M.cents(p.price)};return `<div class="cart-item"><img src="${bundle?byId(p.items[0]).image:p.image}" alt="${esc(bundle?p.title:p.model)}"><div><h3>${esc(bundle?p.title:p.type+' '+p.model)}</h3><p>${bundle?p.tag+' в комплекте · ещё −5%':'Специальная цена жителя'}</p><div class="quantity"><button data-quantity="${line.key}" data-delta="-1" aria-label="Уменьшить количество">−</button><span>${line.qty}</span><button data-quantity="${line.key}" data-delta="1" aria-label="Увеличить количество" ${line.qty>=99?'disabled':''}>+</button></div></div><div class="cart-right"><strong>${fmt(total.price*line.qty)} р.</strong><button class="remove-item" data-remove="${line.key}">Удалить</button></div></div>`;}
function renderPanel(){const container=el('panel-content');if(currentPanel==='cart'){el('panel-title').textContent='Ваша корзина';if(!state.cart.length){container.innerHTML='<div class="panel-empty"><h3>Выберите технику для дома</h3><p>Ваши специальные цены и бонусы уже доступны.</p><button class="button" data-continue>К предложениям</button></div>';return;}const t=M.cartTotals(state.cart,products,bundles);container.innerHTML=state.cart.map(cartItem).join('')+`<div class="cart-summary"><div><span>Товары по обычной цене</span><span>${fmt(t.regular)} р.</span></div><div class="red"><span>Ваша экономия</span><strong>−${fmt(t.saving)} р.</strong></div><div class="total"><span>Итого</span><strong>${fmt(t.price)} р.</strong></div><div class="bonus-total"><span>Начислим бонусами отдельно</span><strong>+${fmt(t.bonus)}</strong></div><button class="button" id="checkout-demo">Перейти к оформлению <span>→</span></button></div><p class="panel-note">Демонстрационная корзина: цены ориентировочные, заказ не отправляется. Доставка рассчитывается при оформлении.</p>`;return;}
if(currentPanel==='favorites'){el('panel-title').textContent='Избранное';container.innerHTML=state.favorites.length?state.favorites.map(id=>{const p=byId(id);return`<div class="mini-product"><img src="${p.image}" alt="${esc(p.model)}"><div><h3>${esc(p.type+' '+p.model)}</h3><strong>${fmt(M.cents(p.price))} р.</strong><br><button class="remove-item" data-favorite="${id}" aria-pressed="true">Удалить из избранного</button></div><button class="button" data-add="p:${id}">В корзину</button></div>`;}).join(''):'<div class="panel-empty"><h3>Сохраните то, что понравилось</h3><p>Нажмите на сердце в карточке товара.</p><button class="button" data-continue>Выбрать технику</button></div>';return;}
if(currentPanel==='compare'){el('panel-title').textContent='Сравнение товаров';if(!state.compare.length){container.innerHTML='<div class="panel-empty"><h3>Что будем сравнивать?</h3><p>Отметьте «Сравнить» в карточках. Можно выбрать до четырёх товаров.</p><button class="button" data-continue>К товарам</button></div>';return;}const list=state.compare.map(byId);container.innerHTML=`<div class="comparison-scroll"><table class="comparison-table"><tbody><tr><th>Товар</th>${list.map(p=>`<td><img src="${p.image}" alt="${esc(p.model)}">${esc(p.type)}<br><b>${esc(p.model)}</b></td>`).join('')}</tr><tr><th>Ваша цена</th>${list.map(p=>`<td><strong>${fmt(M.cents(p.price))} р.</strong></td>`).join('')}</tr><tr><th>Экономия</th>${list.map(p=>`<td class="red">${fmt(M.cents(p.regular-p.price))} р.</td>`).join('')}</tr><tr><th>Бонусы</th>${list.map(p=>`<td class="green">+${fmt(Math.round(M.cents(p.price)*.1))}</td>`).join('')}</tr><tr><th>Характеристики</th>${list.map(p=>`<td>${p.specs.map(esc).join('<br><br>')}</td>`).join('')}</tr><tr><th></th>${list.map(p=>`<td><button class="button" data-add="p:${p.id}">В корзину</button><br><button class="remove-item" data-uncompare="${p.id}">Убрать</button></td>`).join('')}</tr></tbody></table></div>`;return;}
if(currentPanel==='orders'){el('panel-title').textContent='Ваши заказы';container.innerHTML='<div class="panel-empty"><h3>Пока нет оформленных заказов</h3><p>В этом макете можно собрать корзину и увидеть итоговую выгоду.</p><button class="button" data-continue>Выбрать технику</button></div>';return;}
el('panel-title').textContent='Ваши преимущества';container.innerHTML=`<span class="resident-status">${icon('check-circle')}Северный Берег · участник программы</span><div class="account-summary"><strong>Преимущества уже подключены</strong><ul><li>Специальные цены на все 21 товар подборки</li><li>10% от покупки — бонусами</li><li>Ещё 5% скидки на готовые комплекты</li></ul><p>Дополнительная регистрация не требуется.</p></div><p class="panel-note">Показан пример кабинета подтверждённого жителя. Интеграция с приложением и бонусной картой в макете не выполняется.</p>`;}
function openPanel(kind){currentPanel=kind;renderPanel();openDialog(el('panel-dialog'));}
const rooms={kitchen:{src:'assets/kitchen-living-concept.png',alt:'Концепция кухни-гостиной с техникой LG по предоставленной планировке',products:['fridge','oven','hob','dishwasher'],points:[[90,48],[76,64],[75,45],[60,58]]},living:{src:'assets/lounge-concept.png',alt:'Концепция гостиной с телевизором LG и декоративным камином RealFlame',products:['tv','fireplace','bracket'],points:[[76,30],[72,56],[75,43]]}};
function renderRoom(key){activeRoom=key;const r=rooms[key];el('room-image').src=r.src;el('room-image').alt=r.alt;el('room-panel').setAttribute('aria-labelledby','room-'+key);el('room-hotspots').innerHTML=r.products.map((id,i)=>`<button class="hotspot" data-detail="${id}" style="left:${r.points[i][0]}%;top:${r.points[i][1]}%" aria-label="${esc(byId(id).type+' '+byId(id).model)}">${i+1}</button>`).join('');el('room-products').innerHTML=r.products.map((id,i)=>{const p=byId(id);return `<button class="room-product" data-detail="${id}"><img src="${p.image}" width="55" height="65" loading="lazy" alt="${esc(p.model)}"><span>${i+1}. ${esc(p.type)}<b>${esc(p.model)}</b><strong>${fmt(M.cents(p.price))} р.</strong></span></button>`;}).join('');document.querySelectorAll('[data-room]').forEach(b=>{const active=b.dataset.room===key;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});}
document.addEventListener('click',event=>{const target=event.target.closest('button,a');if(!target)return;const d=target.dataset;if(d.detail){productDetail(d.detail);return;}if(d.add){addToCart(d.add);return;}if(d.open){openPanel(d.open);return;}if(d.favorite){const on=state.favorites.includes(d.favorite);state.favorites=on?state.favorites.filter(id=>id!==d.favorite):[...state.favorites,d.favorite];updateStateUI();if(currentPanel==='favorites'&&el('panel-dialog').open)renderPanel();return;}if(d.uncompare){state.compare=state.compare.filter(id=>id!==d.uncompare);updateStateUI();renderPanel();return;}if(d.remove){state.cart=state.cart.filter(x=>x.key!==d.remove);updateStateUI();renderPanel();return;}if(d.quantity){const line=state.cart.find(x=>x.key===d.quantity);if(!line)return;line.qty+=Number(d.delta);state.cart=state.cart.filter(x=>x.qty>0);updateStateUI();renderPanel();return;}if(d.filter){setFilter(d.filter);return;}if(d.category){setFilter(d.category);return;}if(d.room){renderRoom(d.room);return;}if('continue'in d){el('panel-dialog').close();el('catalog').scrollIntoView();return;}if(target.id==='checkout-demo'){el('panel-title').textContent='Расчёт подготовлен';const total=M.cartTotals(state.cart,products,bundles);el('panel-content').innerHTML=`<div class="panel-empty"><h3>Техника для вашего дома</h3><p>К оплате: <strong>${fmt(total.price)} р.</strong><br>После покупки: <strong class="green">+${fmt(total.bonus)} бонусов</strong></p><p>В рабочей версии здесь откроется оформление заказа «5 элемента». Это демонстрационный макет — заказ не отправлен.</p><button class="button" data-continue>Продолжить выбор</button></div>`;return;}});
document.addEventListener('change',event=>{const input=event.target;if(input.matches('[data-compare]')){const id=input.dataset.compare;if(input.checked){if(state.compare.length>=4){input.checked=false;toast('Для сравнения можно выбрать до четырёх товаров');return;}state.compare.push(id);}else state.compare=state.compare.filter(x=>x!==id);updateStateUI();}});
el('sort').addEventListener('change',event=>{sort=event.target.value;renderCatalog();});
el('search').addEventListener('input',event=>{query=event.target.value.trim();filter='all';renderCatalog();});
el('search-form').addEventListener('submit',event=>{event.preventDefault();el('catalog').scrollIntoView();});
el('reset-search').addEventListener('click',()=>setFilter('all'));
el('catalog-button').addEventListener('click',()=>{const menu=el('catalog-menu');menu.hidden=!menu.hidden;el('catalog-button').setAttribute('aria-expanded',String(!menu.hidden));});
document.addEventListener('click',event=>{if(!event.target.closest('.catalog-control')){el('catalog-menu').hidden=true;el('catalog-button').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){el('catalog-menu').hidden=true;el('catalog-button').setAttribute('aria-expanded','false');}});
document.querySelectorAll('[data-room]').forEach(button=>button.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const key=event.key==='Home'?'kitchen':event.key==='End'?'living':activeRoom==='kitchen'?'living':'kitchen';renderRoom(key);el('room-'+key).focus();}}));
el('plan-zoom').addEventListener('click',()=>openDialog(el('plan-dialog')));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.classList.remove('modal-open');});dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});});
el('featured-grid').innerHTML=['fridge','washer','tv','robot'].map(id=>productCard(byId(id))).join('');
el('bundles-grid').innerHTML=bundles.map(bundleCard).join('');renderCatalog();renderRoom('kitchen');updateStateUI();

// Keep the section navigation visibly selected as the reader moves through the page.
const sectionLinks=[...document.querySelectorAll('.section-nav a')];
function markSection(id){sectionLinks.forEach(link=>{const active=link.hash==='#'+id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});}
sectionLinks.forEach(link=>link.addEventListener('click',()=>markSection(link.hash.slice(1))));
let sectionScrollPending=false;
function syncSection(){let current=sectionLinks[0].hash.slice(1);const threshold=document.querySelector('.section-nav').getBoundingClientRect().height+110;for(const link of sectionLinks){const section=el(link.hash.slice(1));if(section&&section.getBoundingClientRect().top<=threshold)current=section.id;}markSection(current);sectionScrollPending=false;}
window.addEventListener('scroll',()=>{if(!sectionScrollPending){sectionScrollPending=true;requestAnimationFrame(syncSection);}},{passive:true});
syncSection();
